name: getFOOOO

on:
  issue_comment:
    types: [ created ]

jobs:
  getprnumber:
    permissions:
      actions: write 
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.pr_number.outputs.number }}
    steps:
      - name: Get PR number
        id: pr_number
        if: ${{ github.event_name == 'issue_comment'}}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUMBER=${PR_URL##*/}
          echo "$PR_NUMBER" >> /tmp/pr_number
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout Pull Request
        if: github.event_name == 'issue_comment'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(cat /tmp/pr_number)
          gh pr checkout $pr_number
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...