name: ScriptInjectionAction

on:
  issue_comment:
    types: [created]

jobs:
  getcomment:
    permission:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Script Injection 
        run: |
          echo ${{ github.event.comment.body }}