name: ScriptInjectionAction

on:
  issue_comment:
    types: [created]

jobs:
  getcomment:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Update comment with workflow run
        uses: actions/github-script@v6
        id: run_outputs
        with:
          script: |
            let commentBody = '${{ github.event.comment.body }}'