name: ScriptInjectionAction

on:
  issue_comment:
    types: [created]

jobs:
  getcomment:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Update comment with workflow run
        uses: actions/github-script@v6
        id: run_outputs
        with:
          script: |
            let commentBody = '${{ github.event.comment.body }}'
            commentBody += `\n\n#### Comment triggered a workflow run

              Started workflow run: [${{ fromJSON(steps.run_outputs.outputs.result).id }}](${{ fromJSON(steps.run_outputs.outputs.result).html_url }})
              * \`recreate_vm: ${{ steps.outputs.outputs.recreate_vm }}\``
            github.rest.issues.updateComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ github.event.comment.id }},
              body: commentBody
            })