name: ScriptInjectionAction

on:
  issue_comment:
    types: [created]

jobs:
  getcomment:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Update comment with workflow run
        uses: actions/github-script@v6
        id: run_outputs
        with:
          github-token: ${{ github.token }}
          script: |
            await new Promise(r => setTimeout(r, 5000));
            let result = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              branch: '${{ steps.comment-branch.outputs.head_ref }}',
              event: 'workflow_dispatch',
              per_page: 10
            });

            var url = result.data.workflow_runs
              .filter(function (e) {
                return e.status != 'completed' && e.status != 'skipped'
            });

            return url[0];