name: ScriptInjectionAction

on:
  issue_comment:
    types: [created]

jobs:
  getcomment:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Script Injection 
        run: |
          echo ${{ github.event.comment.body }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}